# Sugar engine machismo config (SDL3 builds, e.g. Shotgun King current)

[general]
dylib_map = DYLIB_MAP_PATH
patches = PATCHES_PATH

[trampoline.luajit]
lib = libluajit-5.1.so.2
prefix = _lua

[trampoline.game]
override_lib = SUGAR_PATCHES_SDL3_SO
