# Sugar engine machismo config (SDL2 builds, e.g. Wratch's Den)

[general]
dylib_map = DYLIB_MAP_PATH
patches = PATCHES_PATH

[trampoline.luajit]
lib = libluajit-5.1.so.2
prefix = _lua

[trampoline.game]
override_lib = SUGAR_PATCHES_SDL2_SO
